# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_countarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_count',
            field=models.ManyToManyField(to='blog.CountArticle'),
        ),
    ]
