# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_article_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countarticle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
