# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160508_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countarticle',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
